/**
 * Rewrites the report mockup in `marketing/index.html` from the checked-in
 * proof, so the marketing site shows the same audit the app does rather than a
 * hand-written impression of it. Everything between the two marker comments is
 * replaced, and so is the footer's version tag; the surrounding page, and all
 * of the CSS, is hand-maintained.
 *
 *   bun run generate:mockup
 *
 * Run it after `generate:proof` whenever the example fixture changes, and
 * after any version bump so the footer doesn't go stale like it did once
 * already. The markup is a static mirror: the tag and route accordions are
 * wired up by the small script at the foot of `marketing/index.html`, and the
 * one thing it deliberately does not carry over is the stamp that opens the
 * test-code panel, which needs a screenful the hero does not have.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import type { CoverageReport, OperationCoverage, StatusCoverage } from '../lib/api-test-coverage';

const ROOT = path.resolve(import.meta.dirname, '..');
const PROOF = path.join(ROOT, 'app', 'proof.generated.json');
const PAGE = path.join(ROOT, 'marketing', 'index.html');
const MANIFEST = path.join(ROOT, 'package.json');

const START = '<!-- generated by scripts/generate-mockup.ts: do not edit by hand -->';
const END = '<!-- end generated mockup -->';
const VERSION_TAG = /(<span id="r-version">)v[\d.]+(<\/span>)/;

/** The one route left open at rest, so the mockup shows a status list. */
const DEFAULT_OPEN = 'post /tasks';

const CARET =
  '<svg class="r-caret" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" ' +
  'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m6 9 6 6 6-6" /></svg>';

function esc(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/** Render `{param}` segments muted, the way the app's PathInk does. */
function pathInk(specPath: string): string {
  return specPath
    .split(/(\{[^}]+\})/g)
    .filter(Boolean)
    .map((part) => (part.startsWith('{') ? `<em>${esc(part)}</em>` : esc(part)))
    .join('');
}

/** Same rule as the app's verdictOf: assertions first, then the spec. */
function verdictOf(status: StatusCoverage): 'ok' | 'gap' | 'undoc' {
  if (status.assertions === 0) return 'gap';
  return status.documented ? 'ok' : 'undoc';
}

const VERDICT_LABEL = { ok: 'VERIFIED', gap: 'NO TEST', undoc: 'UNDOCUMENTED' } as const;

function slug(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

class Lines {
  private readonly out: string[] = [];

  push(indent: number, line: string): void {
    this.out.push('  '.repeat(indent) + line);
  }

  blank(): void {
    this.out.push('');
  }

  toString(): string {
    return this.out.join('\n');
  }
}

/** The description slot: the spec's own words, or a stamp naming the hole. */
function describe(lines: Lines, indent: number, status: StatusCoverage): void {
  if (!status.documented) {
    lines.push(indent, `<span class="r-code is-absent">${status.code}</span>`);
    lines.push(
      indent,
      `<span class="stamp" data-s="quiet" title="The OpenAPI spec documents no ${status.code} response for this operation">MISSING FROM SPEC</span>`
    );
    return;
  }
  lines.push(indent, `<span class="r-code" data-class="${status.code[0]}">${status.code}</span>`);
  if (status.description) {
    lines.push(indent, `<span class="r-desc">${esc(status.description)}</span>`);
  } else {
    lines.push(
      indent,
      '<span class="stamp" data-s="quiet" title="This response has no description in the OpenAPI spec">NO DESCRIPTION</span>'
    );
  }
}

function renderStatuses(lines: Lines, operation: OperationCoverage): void {
  for (const status of operation.statuses) {
    const verdict = verdictOf(status);
    lines.push(10, '<div class="r-stat">');
    describe(lines, 11, status);
    lines.push(11, '<span class="r-lead" aria-hidden="true"></span>');
    if (verdict !== 'gap') {
      const plural = status.assertions === 1 ? '' : 's';
      lines.push(11, `<span class="r-assert">${status.assertions} assertion${plural}</span>`);
    }
    const label = VERDICT_LABEL[verdict];
    // The stamp is inert here: in the app it opens the test that proves it.
    const title = status.snippets.length
      ? ' title="In the app, this stamp opens the test that proves it"'
      : '';
    const glyph = status.snippets.length ? ' ⌕' : '';
    lines.push(11, `<span class="stamp" data-s="${verdict}"${title}>${label}${glyph}</span>`);
    lines.push(10, '</div>');
  }
}

function renderOperation(lines: Lines, operation: OperationCoverage): void {
  const key = `${operation.method} ${operation.specPath}`;
  const id = `r-op-${slug(key)}`;
  const isOpen = key === DEFAULT_OPEN;
  const total = operation.coveredCount + operation.gapCount;

  lines.push(7, `<div class="r-op"${isOpen ? ' data-open' : ''}>`);
  lines.push(
    8,
    `<button type="button" class="r-row" aria-expanded="${isOpen}" aria-controls="${id}">`
  );
  lines.push(9, `<span class="method" data-m="${operation.method}">${operation.method.toUpperCase()}</span>`);
  lines.push(9, `<span class="path">${pathInk(operation.specPath)}</span>`);
  const marks = operation.statuses
    .map((status) => {
      const state = status.expected ? 'absent' : verdictOf(status);
      return `<span class="mark" data-s="${state}"></span>`;
    })
    .join('');
  lines.push(9, `<span class="marks" aria-hidden="true">${marks}</span>`);
  lines.push(9, `<span class="tally">${operation.coveredCount}/${total}</span>`);
  lines.push(9, CARET);
  lines.push(8, '</button>');
  lines.push(8, `<div class="r-op-body" id="${id}">`);
  lines.push(9, '<div class="r-detail">');
  if (operation.summary) {
    lines.push(10, `<p class="r-detail-sum">${esc(operation.summary)}</p>`);
  } else {
    lines.push(
      10,
      '<p class="r-detail-sum"><span class="stamp" data-s="quiet" title="This operation has no summary in the OpenAPI spec">NO DESCRIPTION</span></p>'
    );
  }
  renderStatuses(lines, operation);
  lines.push(9, '</div>');
  lines.push(8, '</div>');
  lines.push(7, '</div>');
}

function renderMockup(report: CoverageReport): string {
  const lines = new Lines();
  const gaps = report.totalCount - report.coveredCount;
  const verifiedPct = Math.round((report.coveredCount / Math.max(report.totalCount, 1)) * 100);

  lines.push(4, '<div class="r-mast">');
  lines.push(5, `<span class="r-name">${esc(report.repoName)}</span>`);
  lines.push(5, '<span class="r-time">2026-07-30 17:38 UTC</span>');
  lines.push(4, '</div>');
  lines.blank();

  const facts: Array<[string, string]> = [
    ['Operations', String(report.operationCount)],
    ['Status pairs verified', `${report.coveredCount}/${report.totalCount}`],
    ['Gaps', String(gaps)],
    ['Untested routes', String(report.untestedOperations)],
    ['Responses verified', `${verifiedPct}<small>%</small>`]
  ];
  lines.push(4, '<div class="r-summary">');
  for (const [label, value] of facts) {
    lines.push(5, `<span class="cell"><span class="k">${label}</span><span class="v">${value}</span></span>`);
  }
  lines.push(4, '</div>');
  lines.blank();

  lines.push(4, '<div class="r-legend">');
  lines.push(5, '<span><span class="mark" data-s="ok"></span> Verified</span>');
  lines.push(5, '<span><span class="mark" data-s="gap"></span> No test</span>');
  lines.push(5, '<span><span class="mark" data-s="absent"></span> Missing from spec</span>');
  lines.push(5, '<span><span class="mark" data-s="undoc"></span> Undocumented</span>');
  lines.push(4, '</div>');

  for (const tag of report.tags) {
    const id = `r-tag-${slug(tag.tag)}`;
    lines.blank();
    lines.push(4, '<section class="r-sec" data-open>');
    lines.push(5, '<h4 class="r-tag-h">');
    lines.push(6, `<button type="button" class="r-tag" aria-expanded="true" aria-controls="${id}">`);
    lines.push(7, `<span class="r-tag-name">${esc(tag.tag)}</span>`);
    lines.push(7, `<span class="r-tag-desc">${esc(tag.description)}</span>`);
    lines.push(
      7,
      `<span class="tally"><b>${tag.coveredCount}</b>/${tag.totalCount} verified</span>`
    );
    lines.push(7, CARET);
    lines.push(6, '</button>');
    lines.push(5, '</h4>');
    lines.push(5, `<div class="r-tag-body" id="${id}">`);
    lines.push(6, '<div class="r-ops">');
    for (const operation of tag.operations) renderOperation(lines, operation);
    lines.push(6, '</div>');
    lines.push(5, '</div>');
    lines.push(4, '</section>');
  }

  return lines.toString();
}

const report = JSON.parse(readFileSync(PROOF, 'utf8')) as CoverageReport;
const { version } = JSON.parse(readFileSync(MANIFEST, 'utf8')) as { version: string };
const page = readFileSync(PAGE, 'utf8');

const start = page.indexOf(START);
const end = page.indexOf(END);
if (start === -1 || end === -1 || end < start) {
  console.error(`generate-mockup: markers not found in ${path.relative(ROOT, PAGE)}`);
  process.exit(1);
}
if (!VERSION_TAG.test(page)) {
  console.error(`generate-mockup: version tag not found in ${path.relative(ROOT, PAGE)}`);
  process.exit(1);
}

const before = page.slice(0, start + START.length);
const after = page.slice(end);
const withReport = `${before}\n${renderMockup(report)}\n        ${after}`;
const withVersion = withReport.replace(VERSION_TAG, `$1v${version}$2`);
writeFileSync(PAGE, withVersion);

console.log(
  `generate-mockup: ${report.operationCount} operations across ${report.tags.length} tags, v${version} → ${path.relative(ROOT, PAGE)}`
);
